import React from 'react';
import Head from "next/head";
import Link from 'next/link';

export default function Layout({ title, children }) {
  return (
    <>
    <Head>
        <title>{ title ? title + '- Ferreteria' : 'Ferreteria'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <div className='flex min-h-screen flex-col justify-between'>
            <header>
                <nav className='flex h-12 justify-between px-4 items-center shadow-md'>
                    <Link href="/">
                        <h1 className='text-lg  font-bold'>FLR</h1>
                    </Link>
                    <div>
                        <Link href="/cart" className='p-2'>Cart</Link>
                        <Link href="/login" className='p-2'>Login</Link>
                    </div>
                </nav>
            </header>
            <main>
                {children}
            </main>
            <footer>
                footer
            </footer>
        </div> 
    </>
  )
}
